


// export let Datasetdata = {
//     "testcase_id": 606,
//     "name": "Different_data_set",
//     "description": "Testingloginpageforppm",
//     "module_id": 768,
//     "created_at": 1587463728770,
//     "sprints_count": 0,
//     "featurefile_data": null,
//     "cucumber_tags": null,
//     "is_default": false,
//     "is_selected": false,
//     "selected": "",
//     "tc_order": 0,
//     "sprints": null,
//     "datasets": null,
//     "screens_in_testcase": [
//         {
//             "id": 2881,
//             "testcase_id": 606,
//             "screen_id": 1158,
//             "screen_order": 1,
//             "is_default": false,
//             "screen_elements": [
//                 [
//                     {
//                         "element_id": 3612,
//                         "screen_id": 1158,
//                         "web_page_element_id": 451106,
//                         "element_order": 1,
//                         "dataset_values": {
//                             "dataset_value_id": 0,
//                             "dataset_id": 0,
//                             "element_id": 0,
//                             "screen_id": 0,
//                             "input_value": "username-field",
//                             "is_validate": true,
//                             "screen_instance_order": 0,
//                             "dropdown_value": null,
//                             "db_table_name": null,
//                             "db_column_name": null,
//                             "is_click": false,
//                             "is_optional_element": false,
//                             "scroll_required": false,
//                             "validate_text": "username-validate",
//                             "custom_code": false,
//                             "displayed": false,
//                             "element_wait": false,
//                             "scrollup": false,
//                             "scrolldown": false,
//                             "is_random": false,
//                             "is_enter": false,
//                             "cucumber_value": null,
//                             "web_page_elements": null
//                         },
//                         "dataset_values_temp": null,
//                         "web_page_elements": {
//                             "element_id": 451106,
//                             "web_page_id": 1407,
//                             "name": "User Name",
//                             "input_type": "InputText",
//                             "relative_xpath_by_id": null,
//                             "relative_xpath_by_name": null,
//                             "xpath": null,
//                             "is_selected": true,
//                             "tag_name": "input",
//                             "child_id": "User Name",
//                             "child_text": "User Name",
//                             "prefered_field": "xpath_id",
//                             "is_iframe": false,
//                             "iframe_name": null,
//                             "frame_name": null,
//                             "frame_id": null,
//                             "is_frame": false,
//                             "frame_position": 0,
//                             "iframe_position": 0,
//                             "iframe_id": null,
//                             "secondary_input_type": "",
//                             "screen_element_id": 0,
//                             "checked": "checked",
//                             "all_xpaths": "xpath_id=FIELD_VALUE=//input[@id='userName']XPATH_SEPARATORxpath_name=FIELD_VALUE=//input[@name='userName']XPATH_SEPARATORxpath_type=FIELD_VALUE=//input[@type='text']XPATH_SEPARATORxpath_placeholder=FIELD_VALUE=//input[@placeholder='User Name']XPATH_SEPARATORxpath_id_relative=FIELD_VALUE=//div[@id='page_effect-0']/div[1]/inputXPATH_SEPARATORabsolute_xpath=FIELD_VALUE=/html/body[1]/div[3]/div[1]/div[1]/form[1]/div[1]/div[1]/inputXPATH_SEPARATORcss_xpath=FIELD_VALUE=#userNameXPATH_SEPARATORcss_type=FIELD_VALUE=input[type='text']XPATH_SEPARATORcss_placeholder=FIELD_VALUE=input[placeholder='User Name']XPATH_SEPARATORcss_id=FIELD_VALUE=input[id='userName']XPATH_SEPARATORcss_name=FIELD_VALUE=input[name='userName']XPATH_SEPARATOR",
//                             "selected_xpath": "//input[@id='userName']",
//                             "is_old_merge": false,
//                             "is_validate": false
//                         }
//                     },
//                     {
//                         "element_id": 3613,
//                         "screen_id": 1158,
//                         "web_page_element_id": 451108,
//                         "element_order": 2,
//                         "dataset_values": {
//                             "dataset_value_id": 0,
//                             "dataset_id": 0,
//                             "element_id": 0,
//                             "screen_id": 0,
//                             "input_value": "password",
//                             "is_validate": false,
//                             "screen_instance_order": 0,
//                             "dropdown_value": null,
//                             "db_table_name": null,
//                             "db_column_name": null,
//                             "is_click": false,
//                             "is_optional_element": false,
//                             "scroll_required": false,
//                             "validate_text": null,
//                             "custom_code": false,
//                             "displayed": false,
//                             "element_wait": false,
//                             "scrollup": false,
//                             "scrolldown": false,
//                             "is_random": false,
//                             "is_enter": false,
//                             "cucumber_value": null,
//                             "web_page_elements": null
//                         },
//                         "dataset_values_temp": null,
//                         "web_page_elements": {
//                             "element_id": 451108,
//                             "web_page_id": 1407,
//                             "name": "Password",
//                             "input_type": "InputText",
//                             "relative_xpath_by_id": null,
//                             "relative_xpath_by_name": null,
//                             "xpath": null,
//                             "is_selected": true,
//                             "tag_name": "input",
//                             "child_id": "Password",
//                             "child_text": "Password",
//                             "prefered_field": "xpath_id",
//                             "is_iframe": false,
//                             "iframe_name": null,
//                             "frame_name": null,
//                             "frame_id": null,
//                             "is_frame": false,
//                             "frame_position": 0,
//                             "iframe_position": 0,
//                             "iframe_id": null,
//                             "secondary_input_type": "",
//                             "screen_element_id": 0,
//                             "checked": "checked",
//                             "all_xpaths": "xpath_id=FIELD_VALUE=//input[@id='password']XPATH_SEPARATORxpath_name=FIELD_VALUE=//input[@name='password']XPATH_SEPARATORxpath_type=FIELD_VALUE=//input[@type='password']XPATH_SEPARATORxpath_placeholder=FIELD_VALUE=//input[@placeholder='Password']XPATH_SEPARATORxpath_autocomplete=FIELD_VALUE=//input[@autocomplete='off']XPATH_SEPARATORxpath_id_relative=FIELD_VALUE=//div[@id='page_effect-0']/div[2]/inputXPATH_SEPARATORabsolute_xpath=FIELD_VALUE=/html/body[1]/div[3]/div[1]/div[1]/form[1]/div[1]/div[2]/inputXPATH_SEPARATORcss_xpath=FIELD_VALUE=#passwordXPATH_SEPARATORcss_type=FIELD_VALUE=input[type='password']XPATH_SEPARATORcss_name=FIELD_VALUE=input[name='password']XPATH_SEPARATORcss_placeholder=FIELD_VALUE=input[placeholder='Password']XPATH_SEPARATORcss_id=FIELD_VALUE=input[id='password']XPATH_SEPARATORcss_autocomplete=FIELD_VALUE=input[autocomplete='off']XPATH_SEPARATOR",
//                             "selected_xpath": "//input[@id='password']",
//                             "is_old_merge": false,
//                             "is_validate": false
//                         }
//                     },
//                     {
//                         "element_id": 3611,
//                         "screen_id": 1158,
//                         "web_page_element_id": 451091,
//                         "element_order": 3,
//                         "dataset_values": {
//                             "dataset_value_id": 0,
//                             "dataset_id": 0,
//                             "element_id": 0,
//                             "screen_id": 0,
//                             "input_value": null,
//                             "is_validate": false,
//                             "screen_instance_order": 0,
//                             "dropdown_value": null,
//                             "db_table_name": null,
//                             "db_column_name": null,
//                             "is_click": false,
//                             "is_optional_element": false,
//                             "scroll_required": false,
//                             "validate_text": null,
//                             "custom_code": false,
//                             "displayed": false,
//                             "element_wait": false,
//                             "scrollup": false,
//                             "scrolldown": false,
//                             "is_random": false,
//                             "is_enter": false,
//                             "cucumber_value": null,
//                             "web_page_elements": null
//                         },
//                         "dataset_values_temp": null,
//                         "web_page_elements": {
//                             "element_id": 451091,
//                             "web_page_id": 1407,
//                             "name": "login",
//                             "input_type": "Button",
//                             "relative_xpath_by_id": null,
//                             "relative_xpath_by_name": null,
//                             "xpath": null,
//                             "is_selected": true,
//                             "tag_name": "input",
//                             "child_id": "login",
//                             "child_text": "login",
//                             "prefered_field": "xpath_id",
//                             "is_iframe": false,
//                             "iframe_name": null,
//                             "frame_name": null,
//                             "frame_id": null,
//                             "is_frame": false,
//                             "frame_position": 0,
//                             "iframe_position": 0,
//                             "iframe_id": null,
//                             "secondary_input_type": "",
//                             "screen_element_id": 0,
//                             "checked": "checked",
//                             "all_xpaths": "xpath_id=FIELD_VALUE=//input[@id='send']XPATH_SEPARATORxpath_name=FIELD_VALUE=//input[@name='login']XPATH_SEPARATORxpath_type=FIELD_VALUE=//input[@type='submit']XPATH_SEPARATORxpath_value=FIELD_VALUE=//input[@value='Login to your account']XPATH_SEPARATORxpath_id_relative=FIELD_VALUE=//div[@id='page_effect-0']/div[3]/inputXPATH_SEPARATORabsolute_xpath=FIELD_VALUE=/html/body[1]/div[3]/div[1]/div[1]/form[1]/div[1]/div[3]/inputXPATH_SEPARATORcss_xpath=FIELD_VALUE=#sendXPATH_SEPARATORcss_type=FIELD_VALUE=input[type='submit']XPATH_SEPARATORcss_name=FIELD_VALUE=input[name='login']XPATH_SEPARATORcss_value=FIELD_VALUE=input[name='login'][value='Login to your account']XPATH_SEPARATORcss_id=FIELD_VALUE=input[id='send']XPATH_SEPARATOR",
//                             "selected_xpath": "//input[@id='send']",
//                             "is_old_merge": false,
//                             "is_validate": false
//                         }
//                     }
//                 ]
//             ],
//             "screen": {
//                 "screen_id": 1158,
//                 "name": "Login Screen",
//                 "description": "Creating login screen",
//                 "created_at": 1587463655921,
//                 "created_by": 7,
//                 "module_id": 768,
//                 "web_page_id": 1407,
//                 "is_default": false,
//                 "is_select": false,
//                 "regression_screen": false,
//                 "selected": "",
//                 "screen_elements": null,
//                 "regression_screen_elements": null,
//                 "elements": null
//             },
//             "screeninfo": {
//                 "screen_id": 1158,
//                 "name": "Login Screen",
//                 "description": "Creating login screen",
//                 "created_at": 1587463655921,
//                 "created_by": 7,
//                 "module_id": 768,
//                 "web_page_id": 1407,
//                 "is_default": false,
//                 "is_select": false,
//                 "regression_screen": false,
//                 "selected": "",
//                 "screen_elements": null,
//                 "regression_screen_elements": null,
//                 "elements": null
//             }
//         }
//     ],
//     "datasets_list": [
//         {
//             "name": "delet",
//             "description": "deletedesc",
//             "dataset_id": 0,
//             "is_db_dataset": false
//         }
//     ]
// }